spring:
  application:
    name: card_delivery
  datasource:
    driverClassName: org.postgresql.Driver
    password: 0095
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        types:
          print:
            warn :false
    show-sql: true

server:
  port: 8081